// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	component "github.com/godome/godome/pkg/component"
	adapter "github.com/godome/godome/pkg/component/adapter"

	config "github.com/godome/godome/pkg/config"

	logger "github.com/godome/godome/pkg/logger"

	mock "github.com/stretchr/testify/mock"

	post "github.com/godome/examples/pkg/mongodb-simple-blog/blog/post"
)

// PostRepository is an autogenerated mock type for the PostRepository type
type PostRepository struct {
	mock.Mock
}

// Config provides a mock function with given fields:
func (_m *PostRepository) Config() config.Config {
	ret := _m.Called()

	var r0 config.Config
	if rf, ok := ret.Get(0).(func() config.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Config)
		}
	}

	return r0
}

// Create provides a mock function with given fields: data
func (_m *PostRepository) Create(data *post.PostEntity) (*post.PostEntity, error) {
	ret := _m.Called(data)

	var r0 *post.PostEntity
	if rf, ok := ret.Get(0).(func(*post.PostEntity) *post.PostEntity); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.PostEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*post.PostEntity) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAdapter provides a mock function with given fields: adapterName
func (_m *PostRepository) GetAdapter(adapterName string) adapter.Adapter {
	ret := _m.Called(adapterName)

	var r0 adapter.Adapter
	if rf, ok := ret.Get(0).(func(string) adapter.Adapter); ok {
		r0 = rf(adapterName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Adapter)
		}
	}

	return r0
}

// GetOne provides a mock function with given fields: id
func (_m *PostRepository) GetOne(id string) (*post.PostEntity, error) {
	ret := _m.Called(id)

	var r0 *post.PostEntity
	if rf, ok := ret.Get(0).(func(string) *post.PostEntity); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.PostEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logger provides a mock function with given fields:
func (_m *PostRepository) Logger() logger.Logger {
	ret := _m.Called()

	var r0 logger.Logger
	if rf, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}

	return r0
}

// Metadata provides a mock function with given fields:
func (_m *PostRepository) Metadata() component.Metadata {
	ret := _m.Called()

	var r0 component.Metadata
	if rf, ok := ret.Get(0).(func() component.Metadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(component.Metadata)
		}
	}

	return r0
}

// SetAdapter provides a mock function with given fields: _a0
func (_m *PostRepository) SetAdapter(_a0 adapter.Adapter) {
	_m.Called(_a0)
}
