// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	provider "github.com/godome/godome/pkg/provider"
	mock "github.com/stretchr/testify/mock"
)

// HelloworldService is an autogenerated mock type for the HelloworldService type
type HelloworldService struct {
	mock.Mock
}

// GetType provides a mock function with given fields:
func (_m *HelloworldService) GetType() provider.ProviderType {
	ret := _m.Called()

	var r0 provider.ProviderType
	if rf, ok := ret.Get(0).(func() provider.ProviderType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(provider.ProviderType)
	}

	return r0
}

// SayHello provides a mock function with given fields: name
func (_m *HelloworldService) SayHello(name string) string {
	ret := _m.Called(name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
